In [7]:
from datalearn19intro import (get_accounts, get_events, get_subscriptions, get_users)

## Data manipulation
import pandas as pd
import numpy as np

## Modeling
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [124]:
# acc = pd.read_csv("Data/accounts.csv")
acc = get_accounts()
events = get_events()
subs = get_subscriptions()
users = get_users()

In [125]:
# change column names
acc.columns = 'acc_' + acc.columns 
events.columns = 'events_' + events.columns
subs.columns = 'subs_' + subs.columns
users.columns = 'users_' + users.columns

In [167]:
data = acc.copy()

acc_users = pd.merge(acc, users, left_on = 'acc_account_id', right_on = 'users_account_id', how = 'left')
acc_users = acc_users.loc[:, acc_users.columns != 'users_account_id']

acc_users_grouped = acc_users.groupby(['acc_account_id']).users_user_id.nunique().to_frame('unique_users')
acc_users_grouped['unique_cities_of_users'] = acc_users.groupby(['acc_account_id']).users_city.nunique().to_frame('unique_cities_of_users')
## add more aggregations
acc_users_grouped = acc_users_grouped.reset_index()

data = pd.merge(data, acc_users_grouped, 
               on = 'acc_account_id', how = 'left')

In [168]:
data

,acc_account_id,acc_marketing_source,acc_marketing_referrer,acc_created_at,acc_plan_id,acc_trial_start,acc_started_plan_at,acc_signup_box_origin,acc_churn_state,acc_churn_date,...,acc_has_domain,acc_mrr,acc_lead_score,acc_industry.1,acc_team_size,acc_user_goal,acc_user_description,acc_sub_industry,unique_users,unique_cities_of_users
0,2793496,bing,https://www.bing.com/search?q=basecamp login,2019-01-01,NaN,2019-01-01,NaN,NaN,none,NaN,...,0,NaN,0,NaN,NaN,NaN,NaN,NaN,1,1
1,2793497,NaN,NaN,2019-01-01,NaN,2019-01-01,NaN,mobile_app,none,NaN,...,0,NaN,0,NaN,NaN,NaN,NaN,NaN,2,2
2,2793498,adwordsverticals,https://www.google.com/,2019-01-01,NaN,2019-01-01,NaN,NaN,none,NaN,...,0,NaN,0,Other,1,NaN,NaN,NaN,1,1
3,2793499,NaN,NaN,2019-01-01,NaN,2019-01-01,NaN,mobile_app,none,NaN,...,0,NaN,0,NaN,NaN,NaN,NaN,NaN,1,1
4,2793500,adwordsyoutube,https://www.youtube.com/,2019-01-01,NaN,2019-04-04,NaN,NaN,none,NaN,...,0,NaN,0,Design,1,NaN,NaN,NaN,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,2794492,facebook,http://m.facebook.com,2019-01-01,NaN,2019-01-01,NaN,NaN,none,NaN,...,1,NaN,0,NaN,NaN,NaN,NaN,NaN,1,0
997,2794493,instagram,http://instagram.com/,2019-01-01,NaN,2019-01-01,NaN,NaN,none,NaN,...,0,NaN,0,NaN,NaN,NaN,NaN,NaN,1,1
998,2794494,NaN,https://monday.com/,2019-01-01,NaN,2019-01-01,NaN,NaN,none,NaN,...,1,NaN,0,Education,1,NaN,NaN,NaN,1,1
999,2794495,instagram,NaN,2019-01-01,NaN,2019-01-01,NaN,NaN,none,NaN,...,1,NaN,0,NaN,NaN,NaN,NaN,NaN,4,1
1000,2794496,NaN,NaN,2019-01-01,NaN,2019-01-01,NaN,mobile_app,none,NaN,...,0,NaN,0,NaN,NaN,NaN,NaN,NaN,1,0